# Generated by Django 5.1.4 on 2025-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_information_sociallink_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlinesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlines_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(upload_to='airlines_images/')),
            ],
        ),
    ]
