# Generated by Django 5.1.4 on 2025-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_airlineslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Brance_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Swift_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Rounting_Number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
