# Generated by Django 5.1.4 on 2025-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='head_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
