# Generated by Django 5.1.4 on 2025-05-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='Brance_Name',
            new_name='Branch_Name',
        ),
    ]
